/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TidrapporteringRouteImport } from './routes/tidrapportering'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManadsoversiktRouteImport } from './routes/manadsoversikt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUppdragRouteImport } from './routes/admin/uppdrag'
import { Route as AdminKunderRouteImport } from './routes/admin/kunder'
import { Route as AdminKonsulterRouteImport } from './routes/admin/konsulter'
import { Route as AdminAttestRouteImport } from './routes/admin/attest'

const TidrapporteringRoute = TidrapporteringRouteImport.update({
  id: '/tidrapportering',
  path: '/tidrapportering',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManadsoversiktRoute = ManadsoversiktRouteImport.update({
  id: '/manadsoversikt',
  path: '/manadsoversikt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUppdragRoute = AdminUppdragRouteImport.update({
  id: '/admin/uppdrag',
  path: '/admin/uppdrag',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKunderRoute = AdminKunderRouteImport.update({
  id: '/admin/kunder',
  path: '/admin/kunder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKonsulterRoute = AdminKonsulterRouteImport.update({
  id: '/admin/konsulter',
  path: '/admin/konsulter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttestRoute = AdminAttestRouteImport.update({
  id: '/admin/attest',
  path: '/admin/attest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manadsoversikt': typeof ManadsoversiktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tidrapportering': typeof TidrapporteringRoute
  '/admin/attest': typeof AdminAttestRoute
  '/admin/konsulter': typeof AdminKonsulterRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/admin/uppdrag': typeof AdminUppdragRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manadsoversikt': typeof ManadsoversiktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tidrapportering': typeof TidrapporteringRoute
  '/admin/attest': typeof AdminAttestRoute
  '/admin/konsulter': typeof AdminKonsulterRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/admin/uppdrag': typeof AdminUppdragRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manadsoversikt': typeof ManadsoversiktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tidrapportering': typeof TidrapporteringRoute
  '/admin/attest': typeof AdminAttestRoute
  '/admin/konsulter': typeof AdminKonsulterRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/admin/uppdrag': typeof AdminUppdragRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manadsoversikt'
    | '/sitemap.xml'
    | '/tidrapportering'
    | '/admin/attest'
    | '/admin/konsulter'
    | '/admin/kunder'
    | '/admin/uppdrag'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manadsoversikt'
    | '/sitemap.xml'
    | '/tidrapportering'
    | '/admin/attest'
    | '/admin/konsulter'
    | '/admin/kunder'
    | '/admin/uppdrag'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/manadsoversikt'
    | '/sitemap.xml'
    | '/tidrapportering'
    | '/admin/attest'
    | '/admin/konsulter'
    | '/admin/kunder'
    | '/admin/uppdrag'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManadsoversiktRoute: typeof ManadsoversiktRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TidrapporteringRoute: typeof TidrapporteringRoute
  AdminAttestRoute: typeof AdminAttestRoute
  AdminKonsulterRoute: typeof AdminKonsulterRoute
  AdminKunderRoute: typeof AdminKunderRoute
  AdminUppdragRoute: typeof AdminUppdragRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tidrapportering': {
      id: '/tidrapportering'
      path: '/tidrapportering'
      fullPath: '/tidrapportering'
      preLoaderRoute: typeof TidrapporteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manadsoversikt': {
      id: '/manadsoversikt'
      path: '/manadsoversikt'
      fullPath: '/manadsoversikt'
      preLoaderRoute: typeof ManadsoversiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uppdrag': {
      id: '/admin/uppdrag'
      path: '/admin/uppdrag'
      fullPath: '/admin/uppdrag'
      preLoaderRoute: typeof AdminUppdragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kunder': {
      id: '/admin/kunder'
      path: '/admin/kunder'
      fullPath: '/admin/kunder'
      preLoaderRoute: typeof AdminKunderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/konsulter': {
      id: '/admin/konsulter'
      path: '/admin/konsulter'
      fullPath: '/admin/konsulter'
      preLoaderRoute: typeof AdminKonsulterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attest': {
      id: '/admin/attest'
      path: '/admin/attest'
      fullPath: '/admin/attest'
      preLoaderRoute: typeof AdminAttestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManadsoversiktRoute: ManadsoversiktRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TidrapporteringRoute: TidrapporteringRoute,
  AdminAttestRoute: AdminAttestRoute,
  AdminKonsulterRoute: AdminKonsulterRoute,
  AdminKunderRoute: AdminKunderRoute,
  AdminUppdragRoute: AdminUppdragRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
